"""table init

Revision ID: 22e82ab3ff2f
Revises: 
Create Date: 2022-10-13 22:27:49.544627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e82ab3ff2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('campus_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campus_name', sa.String(length=255), nullable=False),
    sa.Column('campus_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('campus_accreditation', sa.String(length=50), nullable=False),
    sa.Column('no_phone', sa.String(length=50), nullable=False),
    sa.Column('fax', sa.String(length=100), nullable=False),
    sa.Column('campus_address', sa.Text(), nullable=False),
    sa.Column('hero_image', sa.String(length=255), nullable=True),
    sa.Column('campus_logo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('campus_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('asal_sekolah', sa.String(length=255), nullable=False),
    sa.Column('jenjang', sa.String(length=100), nullable=False),
    sa.Column('photo_profile', sa.String(length=255), nullable=True),
    sa.Column('home_address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=True)
    op.create_table('campus_faculty',
    sa.Column('campus_faculty_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('faculty_name', sa.String(length=255), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.PrimaryKeyConstraint('campus_faculty_id')
    )
    op.create_table('following',
    sa.Column('following_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('following_id')
    )
    op.create_table('major_campus',
    sa.Column('major_campus_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('major_name', sa.String(length=255), nullable=False),
    sa.Column('faculty_id', sa.BigInteger(), nullable=True),
    sa.Column('major_description', sa.Text(), nullable=True),
    sa.Column('work_prospect', sa.Text(), nullable=True),
    sa.Column('jenjang', sa.String(length=255), nullable=True),
    sa.Column('campus_id', sa.BigInteger(), nullable=True),
    sa.Column('tingkat_keketatan', sa.Integer(), nullable=True),
    sa.Column('major_accreditation', sa.String(length=50), nullable=False),
    sa.Column('kuota_mahasiswa_baru', sa.Integer(), nullable=True),
    sa.Column('jumlah_pendaftaran', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.campus_id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['campus_faculty.campus_faculty_id'], ),
    sa.PrimaryKeyConstraint('major_campus_id')
    )
    op.create_table('major_campus_cost',
    sa.Column('major_campus_cost_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('major_cost_name', sa.String(length=255), nullable=False),
    sa.Column('cost_value', sa.Integer(), nullable=False),
    sa.Column('major_campus_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['major_campus_id'], ['major_campus.major_campus_id'], ),
    sa.PrimaryKeyConstraint('major_campus_cost_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('major_campus_cost')
    op.drop_table('major_campus')
    op.drop_table('following')
    op.drop_table('campus_faculty')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_table('users')
    op.drop_table('campus')
    # ### end Alembic commands ###
